sapphiredev/utilities

- packages/time-utilities/src/lib/DurationFormatter.ts
- packages/time-utilities/src/lib/constants.ts
- packages/time-utilities/tests/lib/duration/DurationFormatter.test.ts
It's sensible to have DurationFormatter default to en-US, since most users will not require language support.
> feat(time-utilities): add defaults for DurationFormatter

- .github/workflows/continuous-integration.yml
- packages/time-utilities/src/index.ts
- packages/time-utilities/src/lib/DurationFormatter.ts
- packages/time-utilities/src/lib/constants.ts
Found a circular import after merging #35 
Then I realized that was not being reported in the CI because the continuous integration was wrong
> refactor: fix circular imports

- packages/discord.js-utilities/src/lib/PaginatedMessage.ts
`addPage`, `addPages`, and `setPages` do not modify `messages`, which is needed when running `resolvePage`. This is a fix for this, as currently the only place that is properly modifying `messages` is in the constructor.
> fix(djs): modifying pages and messages outside of constructor

- packages/discord.js-utilities/src/lib/LazyPaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessage.ts
This PR implements a feature `disableResponseEdit` to the `IPaginatedMessageAction`. This enables developers to have an action only execute without editing the page to the current index.
This PR also includes documentation for the utility as a whole. Some of which was not written the best, so if you think something should be different go right ahead and suggest it.
> feat(discord.js-utilities): add checking index changes and documentation

- packages/discord.js-utilities/src/lib/PaginatedMessage.ts
- Back (◀️) now skips to last page if current index is `0`
- Forward (▶️) now skips to first page if current index is the last page's index.
> feat(discord.js-utilities/pm): minor changes to static defaultActions

- packages/discord-utilities/src/lib/regexes.ts
TSDoc claimed it could be a substring, implementation didn't reflect that.
> fix(discord-utilities): ensure `FormattedCustomEmojiWithGroups` and `ParsedCustomEmojiWithGroups` can be used as substring extraction

- packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts
`MessagePrompter.run` used to be poorly typed, with `unknown`, which prevented users to use `.catch()` or `.then()`. With a simple generic, it was quite easy to deduce the appropriate return type.
The idea of the interfaces to simplify the return types (rather than having a big nested ternary expression) comes from @kyranet
Because the default strategy of the MessagePrompter is the base strategy, I had to cast the return type. Maybe this can be improved
> fix(discord.js-utilities): improve MessagePrompter typings

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- package.json
- packages/discord.js-utilities/package.json
- packages/discord.js-utilities/rollup.config.js
- packages/discord.js-utilities/src/index.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/LazyPaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/index.ts
- yarn.lock
* **discord.js-utilities:** Added TSDoc for many methods
* **discord.js-utilities:** Added caching of messages and handlers to improve performance
* **discord.js-utilities:** Added `addPageBuilder` helper method to make adding pages easier
* **discord.js-utilities:** Added `addPageContent` helper method to make adding pages easier
* **discord.js-utilities:** Added `addPageEmbed` helper method to make adding pages easier
* **discord.js-utilities:** Added `addAsyncPageEmbed` helper method to make adding pages easier. This method is unique from `addPageEmbed` in that the callback can return a `Promise`.
* **discord.js-utilities:** Added `addAsyncPageBuilder` helper method to make adding pages easier. This method is unique from `addPageBuilder` in that the callback can return a `Promise`.
* …
> feat(discord.js-utilities): improve PaginatedMessage

- packages/decorators/src/djs-decorators.ts
- packages/decorators/src/piece-decorators.ts
- packages/decorators/tests/djs/RequiresClientPermissions.test.ts
- packages/decorators/tests/djs/RequiresUserPermissions.test.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- feat(decorators): add default messages to errors thrown by `RequiresPermissions`
- feat(decorators): add `RequiresUserPermissions`
BREAKING CHANGE: `RequiresPermissions` has been renamed to `RequiresBotPermissions`
BREAKING CHANGE: enum entry `DecoratorIdentifiers.RequiresPermissionsGuildOnly` has been changed to `DecoratorIdentifiers.RequiresBotPermissionsGuildOnly`
BREAKING CHANGE: enum entry `DecoratorIdentifiers.RequiresPermissionsMissingPermissions` has been changed to `DecoratorIdentifiers.RequiresBotPermissionsMissingPermissions`
BREAKING CHANGE: i18n identifier `requiresPermissionsGuildOnly` has been changed to `requiresBotPermissionsGuildOnly`
BREAKING CHANGE: i18n identifier `requiresPermissionsMissingPermissions` has been changed to `requiresBotPermissionsMissingPermissions`
> feat(decorators): add user permissions decorator

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
Using the `pageIndexPrefix` property you can set a custom prefix that will be added to each page's
embed footer before the pagination index part.
> feat(discord.js-utilities): add `pageIndexPrefix` static property

- package.json
- packages/fetch/README.md
- packages/fetch/package.json
- packages/fetch/rollup.config.js
- packages/fetch/src/index.ts
- packages/fetch/src/lib/QueryError.ts
- packages/fetch/src/lib/fetch.ts
- packages/fetch/src/lib/types.ts
- packages/fetch/tests/fetch.test.ts
- packages/fetch/tsconfig.json
- yarn.lock
All in all pretty poggers that it can be used in browsers after this
**_Once this is merged then I'll release all utilities packages which includes those for DJS v13._**
BREAKING CHANGE: `fetch` is no longer on the default export. Use a named import instead.
BREAKING CHANGE: This package no longer depends on `node-fetch`
BREAKING CHANGE: This package no longer depends on `@types/node-fetch` for TypeScript users
> feat(fetch): migrate to using cross-fetch

- packages/discord.js-utilities/src/lib/type-guards.ts
- packages/discord.js-utilities/src/lib/utility-types.ts
After merging this PR all of these usages are valid usages:
<details><summary>Click me to expand and see large image</summary>
</details>
We completely dropped the ball on this tbh because the current parameters
straight up don't allow checking for a channel that comes directly from the cache.
> fix(djs-utilities): fixed parameter types for type guards

- packages/discord.js-utilities/src/lib/type-guards.ts
Adds the 3 following thread-related type-guards
- `isNewsThreadChannel`
- `isPublicThreadChannel`
- `isPrivateThreadChannel`
> feat(discord.js-utilities): add more thread-related type guards

- packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/constants.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/index.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterBaseStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterConfirmStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterMessageStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterNumberStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterReactionStrategy.ts
- packages/discord.js-utilities/src/lib/type-guards.ts
- feat(discord.js-utilities): add `isTextBasedChannel` channel type guard
- fix(discord.js-utilities): allow more channel types for MessagePrompter
> fix: message prompter types

- packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/constants.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/index.ts
fix(discord.js-utilities): remove `MessagePrompterStrategies` in favour of `keyof StrategyReturns`
BREAKING CHANGE: `MessagePrompterStrategies` does no exist as it was not mutable with type augmentation
BREAKING CHANGE: If you had custom strategies then be sure to instead module augment `StrategyReturns` with your added keys.
> fix(discord.js-utilities): remove `MessagePrompterStrategies` in favour of `keyof StrategyReturns`

- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterBaseStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterMessageStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategyOptions.ts
You can now give the `editMessage` option to any strategy, and if it is set & the message is editable, then the bot will edit it rather than send a new one.
*Please pack it so I can test it further*
> feat(discord.js-utilities): option to make Prompters edit a message

- packages/discord.js-utilities/src/lib/type-guards.ts
- packages/discord.js-utilities/src/lib/utilities.ts
Although I'm not 100% sure if this logic is correct, cc: @vladfrangu
> fix(discord.js-utilities): account thread channels in permission checks

- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterBaseStrategy.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/utilities/src/lib/utilityTypes.ts
- typedoc.json
With https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/, we'll eventually run into a name conflict between the built-in `Awaited<T>` type, and our type.
This PR fixes the conflict by renaming our type to `Awaitable<T>`
> fix(utilities): rename `Awaited<T>` to `Awaitable<T>`

- packages/discord-utilities/src/lib/regexes.ts
This pattern can be found when you hold Shift and hover over a message, and click the "ID" button.
It is needed for https://github.com/sapphiredev/framework/pull/292
> feat(discord-utilities): add channelId-messageId regex

- package.json
Yarn v3 no longer has the `--latest` flag. [docs](https://yarnpkg.com/cli/upgrade-interactive)
> build: remove unsupported yarn flag

- packages/eslint-config/src/index.ts
- packages/eslint-config/tests/__snapshots__/eslint.test.ts.snap
Use [`@typescript-eslint/no-duplicate-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-duplicate-imports.md) instead of `no-duplicate-imports`.
> This rule extends the base `eslint/no-duplicate-imports` rule. This version adds support for type-only import and export.
> fix(eslint-config): allow type and regular imports

- packages/discord-utilities/src/index.ts
- packages/discord-utilities/src/lib/limits.ts
Add different limits related to discord.
I have intentionnally missed a few ones such as the one bellow, because i wanted your opinion:
- max # of persons in a channel with a video [25]
- max # of guilds for a classic / nitro user (why would a bot need that?) [100 / 200 i think]
- ~~max # of members in a guild (if you reach max you can ask discord for more so this isn't a hard limit) [500k]~~ available in discord.js
- other limits that can be 💥 with boosts, such as max # of emojis/stickers per guild and max upload size [50 / 0 / 8Mo, 100 / 15 / 8Mo, 150 / 30 / 50Mo, 250 / 60 / 100Mo]
> feat(discord-utilities): add discord limits

- packages/time-utilities/src/lib/DurationFormatter.ts
- packages/time-utilities/src/lib/constants.ts
You can specify a left and right separator that is inserted as so `<left>UNIT<right>` when calling `.format()`
Example:
```typescript
const default_units = new DurationFormatter();
const custom_units = new DurationFormatter({
second: { DEFAULT: "s" },
minute: { DEFAULT: "m" },
hour: { DEFAULT: "h" },
day: { DEFAULT: "d" },
week: { DEFAULT: "w" },
month: { DEFAULT: "m" },
year: { DEFAULT: "y" },
});
console.log(default_units.format(120_000_000, 7));
// 1 day 9 hours 20 minutes
console.log(default_units.format(120_000_000, 7, { left: " ", right: ", " }));
// 1 day, 9 hours, 20 minutes
console.log(custom_units.format(120_000_000, 7, { left: "", right: " " }));
// 1d 9h 20m
```
The left and right separators default to a space.
> feat(DurationFormatter): added separators for joining units

- packages/snowflake/src/lib/DiscordSnowflake.ts
- packages/snowflake/src/lib/Snowflake.ts
- packages/snowflake/src/lib/TwitterSnowflake.ts
- packages/snowflake/tests/lib/DiscordSnowflake.test.ts
- packages/snowflake/tests/lib/Snowflake.test.ts
- packages/snowflake/tests/lib/TwitterSnowflake.test.ts
- **fix**: limit range of `processId` to 5 bits
- **fix**: limit range of `workerId` to 5 bits
- **feat**: added `epoch` getter
- **feat**: added `timestampFrom` method
- **feat**: default `processId` to `process.pid`
- **feat**: default `workerId` to `worker_threads.threadId`
- **refactor**: improved performance and reduced amount of checks
- :warning: **BREAKING CHANGE**: Renamed `processID` to `processId`
- :warning: **BREAKING CHANGE**: Renamed `workerID` to `workerId`
- :warning: **BREAKING CHANGE**: `processId` not longer defaults to 1n (outside NODE_ENV = test)
- :warning: **BREAKING CHANGE**: `workerId` not longer defaults to 1n (outside NODE_ENV = test)
- :warning: **BREAKING CHANGE**: `DiscordSnowflake` is not longer a class, but a constructed Snowflake
- :warning: **BREAKING …
> feat(Snowflake): rework entire package

- packages/snowflake/src/lib/Snowflake.ts
This makes browser bundling easier, besides, process IDs and thread IDs are 32-bit integers, which we cannot fit in 5 bits, so there wasn't a real guarantee of uniqueness across threads or servers.
> fix(snowflake): remove env-based defaults

- packages/event-iterator/package.json
- packages/event-iterator/rollup.config.js
- packages/event-iterator/src/index.ts
- packages/event-iterator/src/tsconfig.json
- packages/event-iterator/tests/lib/MockEmitter.ts
- packages/event-iterator/tests/tsconfig.json
- packages/event-iterator/tsconfig.json
- yarn.lock
Not sure why we ever even did because there is no `EventEmitter` in browsers which AFAIK this relies on.
> feat(event-iterator): do not bundle for browsers

- packages/utilities/src/lib/utilityTypes.ts
The `{}` type allowed any value (even numbers and strings), which wasn't different to `unknown` except that it required non-null. By doing an union (`{} & object`), the type is required to be both an object and non-null.
> fix(utilities): make `NonNullObject` require object

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedFieldMessageEmbed.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageEmbedFields.ts
`PaginatedMessageEmbedFields` (this new one) differs from `PaginatedFieldMessageEmbed` (Kanama's one) as the items here are whole fields, that are added to the embed, whereas `PaginatedFieldMessageEmbed` concatenates the items in a single field with a given formatter function.
I believe this one is quite useful too and will find its lot of users.
> feat(discord.js-utilities): add `PaginatedMessageEmbedFields`

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
This makes it possible to add `LINK` style buttons to the paginated message's actions.
Previously it was set up to lock out this possibility.
I probably had some issues implementing it in a sensible way and gave up, I don't remember.
I also made it possible to set a second optional parameter of `setActions` to true
to have the library merge in `PaginatedMessage.defaultActions`, something that is a
common use case when using this particular function.
This change will save users from having to manually add the default actions.
I'm not sure if this change should be considered `semver:major`. @vladfrangu what do you say?
I'm primarily asking because `PaginatedMessageAction` was changed from an `interface` to a `type`
which subsequently caused this issue at least in Skyra's code:
Easily fixed …
> feat(PaginatedMessage): made it possible to add custom `link` buttons with `setActions` / `addActions` / `addAction`

- packages/decorators/src/piece-decorators.ts
BREAKING CHANGE: When using `@ApplyOptions` with a callback function, the single parameter of `PieceContex` been changed to an object, which also has a property of `Container`. Migration change is `@ApplyOptions<Listener.Options>(({ context }) => ({`
> feat(decorators): add container to `ApplyOptions` callback

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedFieldMessageEmbed.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageEmbedFields.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
Tested:
Only didn't *really* check previously replied to interactions but the PaginatedMessage itself gets `.replied` set to true after 1 ButtonInteraction which I did test so that comes down to the same thing.
> feat(PaginatedMessage): add support for interactions

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
I honestly don't even really get it but it does solve the issue. For some reason with the following code, the pagination footer was applied incorrectly
**Code:**
```ts
import { PaginatedMessage } from '@sapphire/discord.js-utilities';
import { Command } from '@sapphire/framework';
import { Message, MessageEmbed } from 'discord.js';
const myMessage = new PaginatedMessage({
template: new MessageEmbed().setColor('#FF0000').setFooter({
text: ' Official Bot from server'
})
});
export class UserCommand extends Command {
public override async messageRun(msg: Message) {
await msg.channel.sendTyping();
myMessage
.addPageEmbeds((embed1, embed2, embed3) => {
// You can add up to 10 embeds
embed1.setColor('#FF0000').setDescription('example description 1'); …
```
> fix(PaginatedMessage): fix footer application when there are multiple embeds

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
This PR adds support for [Context Menu Interactions](https://discord.js.org/#/docs/discord.js/stable/class/ContextMenuInteraction) to be passed in for paginated messages.
> feat(PaginatedMessage): support context menu interactions

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
This introduces a new potential emitted warning when the client is not
properly configured to handle DM commands.
Whether the warning is emitted at all can be configured so people can choose to not get it at all.
It will also only be emitted once per instance of PaginatedMessage.
On the note of the warning being per instance of PaginatedMessage, yes that does often mean that
people will get it for every time that `run` is called because it's common (and recommended)
to call `new PaginatedMessage` inside of the `*Run` method.
I don't think it's fitting to keep track of that boolean outside of the class though.
Calling run twice example:
> feat(PaginatedMessage): emit warning when running in a DM channel without required client options

- packages/discord-utilities/src/lib/regexes.ts
A token regex can be useful for automatically resetting tokens, and validating tokens before making requests or connecting to the gateway.
Source is from searching TOKEN_REGEX in https://canary.discord.com/assets/2fa49c2711296797d83c.js
> feat(discord-utilities): Add token regex

- packages/discord-utilities/src/lib/regexes.ts
Its been discord.com for a while, and this regex does not work for current webhooks
Also made it match API versions since those work too
> fix(discord-utilities) update webhook regex

- packages/utilities/src/index.ts
- packages/utilities/src/lib/toTitleCase.ts
- packages/utilities/tests/toTitleCase.test.ts
This PR adds functionality to add your own variants and case sensitivity for `toTitleCase()`
```ts
import { totTitleCase } from '@sapphire/utilities';
toTitleCase('json textchannel', { additionalVariants: { json: 'JSON' } }); // 'JSON TextChannel'
toTitleCase('jSON textChannel', { additionalVariants: { json: 'JSON' }, caseSensitive: true }; // 'Json Textchannel'
```
- Add `options` parameter to `toTitleCase()` function along with it's functionality and tests.
- Rename `TOTITLECASE` to `TO_TITLE_CASE`
- Rename `titleCaseVariants` to `baseVariants`
- Use `String#substring()` instead of `String#substr()` as it's deprecated.
This feature should be released as semver minor.
> feat(utlities): add title case `options` param

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
**Updated the applyFooter() function so it only applies the footer to the last embed of the page.**
_This prevents the footer to be repeated multiple times on a single page, when the page has multiple embeds (added with PaginatedMessage.addPageEmbeds(), for example)._
> fix(PaginatedMessage): removed duplicate page index footers on multiple embed pages

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
Currently this mismatch causes a type build issue when implementing the static methods:
```ts
import { LanguageKeys } from '#lib/i18n/languageKeys';
import { PaginatedMessage } from '@sapphire/discord.js-utilities';
import { container } from '@sapphire/framework';
import i18n from 'i18next';
PaginatedMessage.selectMenuOptions = async (pageIndex, internationalizationContext) => {
const languageForContext = await container.i18n.fetchLanguage(internationalizationContext);
return { label: `${i18n.t(LanguageKeys.Globals.PaginatedMessagePage, { lng: languageForContext ?? 'en-US' })} ${pageIndex}` };
};
```
> fix(PaginatedMessage): update i18nContext to match plugin-i18next

- packages/discord-utilities/src/lib/limits.ts
This PR changes two limits to align with the ddev documentation:
- [custom placeholder text if nothing is selected, max 150 characters](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure)
- [autocomplete choices (max of 25 choices)](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-autocomplete)
> fix(limits): align with ddev docs

- packages/decorators/src/djs-decorators.ts
- packages/fetch/README.md
- packages/fetch/src/lib/types.ts
- packages/fetch/tests/fetch.test.ts
- packages/time-utilities/src/lib/constants.ts
To be frank I don't know why exactly but @vladfrangu told Kyra to remove it for lexure here https://github.com/sapphiredev/utilities/pull/388/files#r917235502 so I assume the others should go also
> refactor: change `const enum` for regular `enum`

- packages/result/README.md
- packages/result/package.json
- packages/result/src/lib/Option.ts
- packages/result/src/lib/Result.ts
- packages/result/tests/Option.test.ts
- packages/result/tests/Result.test.ts
The README's code wasn't... correct at all.
Also re-exports `ok`, `err`, `some`, and `none` for convenience and for parity with Rust.
> feat(result): export `ok`, `err`, `some`, `none`, and improve docs

- packages/result/src/lib/Option/IOption.ts
- packages/result/src/lib/Option/Some.ts
- packages/result/src/lib/Result/IResult.ts
- packages/result/src/lib/Result/Ok.ts
- packages/result/tests/Option.test.ts
- packages/result/tests/Result.test.ts
#415 but fixed.
Please make sure it's *satisfiable*, and that it solves the type issues you had, @Favna.
> fix(result): better `unwrapOr*`, added more tests

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
- packages/discord.js-utilities/src/lib/type-guards.ts
- packages/discord.js-utilities/src/lib/utility-types.ts
needs rebase
- feat(discord.js-utilities): add `ChatInputOrContextMenuInteraction`, `NonModalInteraction`, and `AnyInteraction` utility types
- feat(discord.js-utilities): rename `runsOnInteraction` to `isAnyInteraction` and add deprecation notice for the former
> feat/discordjs utilities migrate runsOnInteraction

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
Resolves #424 
```
BREAKING CHANGE: removed deprecated `author` field on `PaginatedMessage` 
BREAKING CHANGE: removed deprecated function `runsOnInteraction `
```
> refactor(djs-utilities)!: remove deprecated code

- packages/async-queue/src/lib/AsyncQueue.ts
- packages/async-queue/src/lib/AsyncQueueEntry.ts
- packages/async-queue/tests/AsyncQueue.test.ts
Too Many Requests on AQ, but this should make https://github.com/discordjs/discord.js/issues/8497 a lot more efficient.
Also added `AsyncQueue#queued` which makes more sense to have now that we have a head system.
> feat: add `AsyncQueue#abortAll`

- packages/result/src/lib/Option/IOption.ts
- packages/result/src/lib/Option/None.ts
- packages/result/src/lib/Option/Some.ts
- packages/result/src/lib/Result/Err.ts
- packages/result/src/lib/Result/IResult.ts
- packages/result/src/lib/Result/Ok.ts
- packages/result/tests/Option.test.ts
- packages/result/tests/Result.test.ts
This comes very handy for swapping Results and Options with Promises, take the example below:
```typescript
const result = await Result.fromAsync(fetch('https://example.org/image.png'));
return result
.map(async (response) => {
const blob = await response.blob();
return { name: 'image.png', data: await blob.arrayBuffer(), type: blob.type };
})
.intoPromise();
```
Which is a lot more idiomatic than:
```typescript
const result = await Result.fromAsync(fetch('https://example.org/image.png'));
return result.match({
ok: async (response) => {
const blob = await response.blob();
return { name: 'image.png', data: await blob.arrayBuffer(), type: blob.type };
},
err: (error) => Promise.resolve(err(error))
});
```
> feat: add `intoPromise`

- packages/utilities/src/lib/isNumber.ts
This PR is due to the fact that this utility cannot accept a string as a value, so what has to be done is:
```ts
const numberString = '1';
isNumber(Number(numberString));
```
With this PR you will now be able to do the following:
```ts
const numberString = '1';
isNumber(numberString);
```
This helps for example, if you have an API and you receive a query parameter, this will come in string type, with this you can validate directly without the need to convert it to a number manually.
> fix(isNumber): parse string parameter as number (allow string as parameter)

- packages/result/src/lib/Result/Err.ts
- packages/result/src/lib/Result/IResult.ts
- packages/result/src/lib/Result/Ok.ts
- packages/result/tests/Result.test.ts
This is essentially a shortcut for:
```ts
return result.match({
err: (error) => {
throw error;
},
ok: (value) => value.data[0]
});
```
which can then be written as:
```ts
return result.map((value) => value.data[0]).unwrapRaw();
```
This is useful when instead of throwing a `ResultError` you want to instead throw the inner error (i.e. `ArgumentError` for Sapphire, see sapphiredev/framework#528, or a `FetchError` from @skyra/safe-fetch, something that brought about this change)
> feat(result): add `Result.unwrapRaw`

- packages/utilities/src/index.ts
- packages/utilities/src/lib/sleep.ts
- packages/utilities/src/tsconfig.json
- packages/utilities/tests/sleep.test.ts
- packages/utilities/tests/tsconfig.json
- packages/utilities/tests/util/macros/comparators.ts
This pr adds `sleep` and `sleepAsync` 
I'm not using `timers/promise` just to make it browser compitible
> feat(utilities): add `sleep` and `sleepSync`

- packages/eslint-config/package.json
- packages/eslint-config/tsup.config.ts
- packages/prettier-config/package.json
- packages/prettier-config/tsup.config.ts
- scripts/subpath-updater.mjs
This pr also removes `dts` files from eslint and prettier config.
I tried to use [--silent](https://github.com/egoist/tsup/search?q=silent) flag for the `dependsOn` builds to hide some logs but idk how can I pass the flags to the build script from `dependsOn`
> chore: improve subpath check message

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
This pull request fixes a bug where the button components won't get removed due to a race condition error: `DiscordAPIError: Interaction has already been acknowledged.`.
This occurs when the user tries to interact with the message when the paginated message is about to close.
You can reproduce this by spam clicking the next/previous buttons on a paginated message.
> fix(utilities): race condition issue for closed paginated message

- packages/duration/tests/lib/DurationFormatter.test.ts
The Time enum is already exported in `constants.ts`. It's worth noting that `/timestamp` also exports the same enum, but I think it would be a bit overkill to create another package just to share one small enum. It does bring up the question of whether the packages usages should copy and paste the same `Time` documentation?
> refactor(duration): reuse Time enum

- packages/discord-utilities/src/lib/limits.ts
This PR updates the `MaxNitroUploadLimit` property in the `discord-utilities` package to the new limit.
> fix(discord-utilities): fix nitro upload limit

- packages/discord.js-utilities/src/lib/utilities.ts
This resolves a bug in the permission functions that is caused by a bot receiving a message in an unsupported channel, which currently includes forum channels until Sapphire supports DJS v14.
> fix(discord.js-utilities): added null checks for permission checks

- packages/snowflake/src/lib/TwitterSnowflake.ts
- packages/snowflake/tests/lib/TwitterSnowflake.test.ts
Partially fixes #521 by updating the epoch to be `1288834974657`, found [here](https://github.com/twitter-archive/snowflake/blob/b3f6a3c6ca8e1b6847baa6ff42bf72201e2c2231/src/main/scala/com/twitter/service/snowflake/IdWorker.scala#L25) in twitter's archived snowflakes repository
The rest of the issue is deciding what to do (if anything) about non-snowflake tweet ids. Since TwitterSnowflake is deliberately focused on twitter, I'd expect them to be rejected, since they're just numbers, not snowflakes, and would return mismatched data vses. twitter if ever deconstructed.
oduwsdl/tweetedat uses [this](https://github.com/oduwsdl/tweetedat/blob/eae40b65ac99a05b596e75ac7ed015ee6134ab82/index.html#L2500-L2503) check to filter out non-snowflakes, but I don't know how to verify if that's correct, …
> fix(snowflake): TwitterSnowflake using incorrect epoch

- packages/snowflake/src/lib/Snowflake.ts
- packages/snowflake/tests/lib/Snowflake.test.ts
Useful for sorting structures by snowflakes, also does string length comparison when both values are strings to avoid false positives, as `a < b` (as both strings) will do an alphabetical order sort rather than a number sort.
> feat(snowflake): added `Snowflake.compare`

- packages/ratelimits/package.json
- packages/ratelimits/src/lib/RateLimitManager.ts
- turbo.json
- yarn.lock
ref: https://twitter.com/syjalo_/status/1633737653806940161
This ensures that the package is serverless ready where it is not
possible to install Node dependencies.
> refactor(ratelimits): remove dependency on `@sapphire/timer-manager`

- packages/eslint-config/tests/__snapshots__/eslint.test.ts.snap
- packages/prettier-config/tests/__snapshots__/prettier.test.ts.snap
- packages/utilities/src/lib/chunk.ts
Tested on an array with 21 elements:
| Version |   100,000 |      % | 1,000,000 |      % |
| :-----: | :-------: | :----: | :-------: | :----: |
| Old     | 257.704ms |   100% |    2.163s |   100% |
| New     | 162.308ms | 62.98% |    1.532s | 70.82% |
The updated function also uses half as much memory, as it doesn't clone the array. The performance improvement should be even greater on larger arrays, as removing (or inserting) elements at the start of an array is the slowest array operation.
> perf(chunk): remove clone

- packages/snowflake/src/lib/Snowflake.ts
This simplifies and optimizes same-type checks, which are likelier than mismatching types, the benchmarks below are run on 100,000,000 iterations:
| Pair               | Old      | New      | Comparison |
| :----------------: | :------: | :------: | :--------: |
| `string`, `string` | 43.623ms | 37.412ms |     85.76% |
| `string`, `bigint` |   8.242s |   8.576s |    104.05% |
| `bigint`, `bigint` |   2.028s |   1.904s |     93.88% |
> refactor(Snowflake): simplify `compare` logic

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
Adds a method to update page content after `PaginatedMessage` has run, allowing more interactivity when handling buttons.
Example:
```ts
run: async ({ handler }) => {
const value = Math.floor(Math.random() * 10);
await handler.updateCurrentPage({
embeds: [
new EmbedBuilder().setDescription(`${value}`)
]
});
}
```
> feat(PaginatedMessage): add method to update pages after response

- packages/discord.js-utilities/src/lib/PaginatedMessages/LazyPaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
Per-page components for `PaginatedMessage` are now supported.
Page actions can be added by using the 3 methods `setPageActions`, `addPageActions`, and `addPageAction`.
> feat(PaginatedMessage): add support for per-page actions

- packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/index.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterBaseStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterConfirmStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterMessageStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterNumberStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterReactionStrategy.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
- packages/discord.js-utilities/src/lib/type-guards.ts
Closes #533 
Adds support for `UserSelectMenu`, `RoleSelectMenu`, `MentionableSelectMenu`, and `ChannelSelectMenu` as action types.
> feat(PaginatedMessage): add support for all select menus

- package.json
- packages/async-queue/package.json
- packages/bitfield/package.json
- packages/cron/package.json
- packages/decorators/package.json
- packages/discord-utilities/package.json
- packages/duration/package.json
- packages/eslint-config/package.json
- packages/eslint-plugin-result/package.json
- packages/event-iterator/package.json
- packages/fetch/package.json
- packages/lexure/package.json
- packages/lexure/tests/lib/ArgumentStream.test.ts
- packages/node-utilities/package.json
- packages/prettier-config/package.json
- packages/ratelimits/package.json
- packages/result/package.json
- packages/snowflake/package.json
- packages/stopwatch/package.json
- packages/timer-manager/package.json
- packages/timestamp/package.json
- packages/ts-config/package.json
- packages/utilities/package.json
- yarn.lock
The methods were renamed around, the two methods we used were clearing the implementation, `mockClear` only resets the state.
https://github.com/vitest-dev/vitest/blob/77d071a91f81b6faef28cb30c6c5b617a661459d/packages/spy/src/index.ts#L224-L242
> chore(deps): update `vitest`

- packages/bitfield/src/lib/BitField.ts
This drastically improves performance of the `toArray` and `toObject` methods.
For the record about "but we don't use symbols for privates anywhere!", we still support Node.js v16, which has horrible `#private` performance, and tsup compiles the `#private` fields as weakmaps, nullifying the performance gains.
> refactor(bitfield): call entries only once

- packages/snowflake/src/lib/Snowflake.ts
- packages/snowflake/tests/lib/Snowflake.test.ts
This PR also switches `#private` properties to symbol properties for higher performance. Also added missing tests to near 100% coverage.
> feat(snowflake): expose `processId` and `workerId`

- packages/snowflake/src/lib/Snowflake.ts
- packages/snowflake/tests/lib/Snowflake.test.ts
This fixes several issues at once, and also increases performance.
- The code was cycling at 4095, making the effective range [0, 4094] instead of [0, 4095].
- When passing a custom increment over the limit (>4095), it would be set to 0, which can cause duplication issues.
- When passing a custom increment that was <=4095, it would call the `else` branch which would then override with the defaults.
- Were custom increments to be allowed, negative values would overflow the rest of the data. For example, fixing the branching code:
```js
DiscordSnowflake.generate({ increment: -1n, timestamp: 1600000000000n, processId: 1n, workerId: 0n });
```
Would return... `-1`, which is can be deconstructed as:
```js
{
id: -1n,
timestamp: 1420070399999n,
workerId: 31n,
processId: 31n,
increment: 4095n, …
```
> refactor(snowflake): handle out-of-bounds `increment` correctly

- packages/discord.js-utilities/README.md
- packages/discord.js-utilities/src/lib/PaginatedMessages/LazyPaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
There were a few types in the `PaginatedMessage` class which didn't reflect how the class actually resolves things. This brings them in-line with their actual behaviour.
- Allowing `run` on actions to be optional means they can be resolved in interaction handlers rather than just `PaginatedMessage`. This is useful if the button/menu contains a lot of business logic and you want it to have its own piece, or you're passing data in the custom ID.
- `PaginatedMessageMessageOptionsUnion` now omits the `components` property since it was never handled in the first place. Originally, you could pass `components` in the message options without any issues, however the class never used that property and instead resolved the components from `actions`.
- The callback union type is removed from …
> refactor(PaginatedMessage): update types and make `run` on actions optional

- packages/bitfield/src/lib/BitField.ts
- packages/bitfield/tests/lib/BitField.test.ts
The discord.js counterpart supports has [`[Symbol.iterator]`](https://github.com/discordjs/discord.js/blob/46167a79d7d0cac5599459a31c33b2bbcf6e06da/packages/discord.js/src/util/BitField.js#L143-L147) but we didn't support any kind of iteration, so I added the iterator methods to conform to an iterable's methods (`.keys()`, `.values()`, and `.entries()`).
> feat(bitfield): add iterator methods

- packages/utilities/tests/sleepSync.test.ts
We're using a spy for `Date.now()` instead of a fake timer. This is because `sleepSync()` does not use timers, but instead checks against `Date.now()`'s value.
> test(sleepSync): use spies for `Date.now()`

- packages/discord.js-utilities/src/index.ts
- packages/ts-config/tsconfig.json
This fixes a bug that caused end-users to often need to install `tslib`
manually and add a line `import 'tslib'` at the top of their entrypoint
files because `require('tslib')` is no longer being automatically added by
typescript after setting `"module": "Node16"` in `tsconfig.json`.
Many of our own libraries and those of other users were affected by this
and the better solution is to just emit the helper methods so tslib imports
are no longer needed, and users can use our config without needing extra
steps. If they do still want to not have the helpers emitted, they can
just toggle the option to false and import tslib instead.
Example given `@sapphire/discord.js-utilities`, specifically `dist/index.js`
**before**
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: …
```
> fix(tsconfig): set `noEmitHelpers` to false

- packages/utilities/src/lib/poll.ts
- packages/utilities/tests/poll.test.ts
- packages/utilities/tests/pollSync.test.ts
Using `AbortSignal`, added more options to further customize `poll`'s behaviour.
>  refactor(utilities): rewrite poll function

- packages/ts-config/README.md
Corrects a grammatical mistake that had given the impression that certain strict compiler options weren't being configured correctly.
> docs(ts-config): update readme

- packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterConfirmStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterMessageStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterNumberStrategy.ts
- packages/discord.js-utilities/src/lib/MessagePrompter/strategies/MessagePrompterReactionStrategy.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
Now that the rewrite is up and live, I updated the links. `@discord.js-utilities` was the only package referencing djs's docs, so only one package was updated.
> docs(discord.js-utilities): update discord.js.org links

- packages/discord-utilities/src/lib/limits.ts
Changes:
- feat: added `MaximumNitroBasicUploadSize` (50MB)
- fix: increase `MaximumUploadSize` from 8MB to 25MB
- fix: adjusted `MaximumNitroUploadSize` from 5GB to 500MB
- fix: adjusted `MaximumUploadSizeInGuild`'s first two values from 8MB to 25MB
> feat(utilities): add maximum nitro basic upload size

- packages/discord.js-utilities/src/lib/PaginatedMessages/LazyPaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedFieldMessageEmbed.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageEmbedFields.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
List of changes:
- feat(PaginatedMessage): add `JSONEncodable<APIEmbed>` support
- feat(PaginatedFieldMessageEmbed): add `JSONEncodable<APIEmbed>` support
- feat(PaginatedMessageEmbedFields): add `JSONEncodable<APIEmbed>` support
- refactor(LazyPaginatedMessage): remove useless overriding methods
- refactor(PaginatedFieldMessageEmbed): make template always `APIEmbed`
- refactor(PaginatedMessageEmbedFields): make template always `APIEmbed`
> feat(PaginatedMessage): improve `@discordjs/builders` support

- packages/utilities/src/lib/tryParseJSON.ts
- packages/utilities/tests/tryParseJSON.test.ts
Just like `tryParseJSON`'s types are hardened in relation to the `JSON.parse` counterpart, the `replacer` function is also hardened.
> feat(tryParseJSON): support `replacer` argument

- packages/fetch/src/lib/types.ts
This is faintly related to #694, however, this time the issue is fixed from the @sapphire/fetch side of things. The way tsup is bundling our package is by putting the content from `src/lib/types.ts` (interfaces and enums) at the top of the `index.d.ts`/`index.d.mts` file without hoisting the reference lib comment to the top. TS then sees DOM code being used _above_ the reference lib comment and says that the DOM code is not available when compiling.
By adding a reference lib comment in `types.ts` it will be put at the top of the `index.d.ts`/`index.d.mts` file and the issue is resolved.
> fix(fetch): add additional reference lib comment

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
Previously link buttons didnt get added properly when using `setActions`/`addAction`/`addActions` because we didn't properly check for Link style buttons.
Despite adding 3 buttons this caused PaginatedMessages such as:
After applying these changes it is correctly instead:
> fix(PaginatedMessage): fixed link buttons not properly being added

- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
This is a side effect of sorts of #698. Previously this issue wasn't really brought to light because Link buttons didn't get added properly. While it's purely subjective, I think link buttons should go below the select menu. This way the order is consistent across PaginatedMessages:
1. Action buttons
1. Select menus
1. Link buttons
> refactor(PaginatedMessage): always put link buttons below select menus

- .eslintrc
- packages/utilities/package.json
- packages/utilities/src/index.ts
- packages/utilities/src/lib/omitKeysFromObject.ts
- packages/utilities/tests/omitKeysFromObject.test.ts
Ported from https://github.com/skyra-project/skyra/pull/2505#discussion_r1390246482 where I commented that the new utility function from Skyra would do well to be ported to Sapphire Utilities.
> feat(utilities): add omitKeysFromObject utility function

- packages/event-iterator/src/index.ts
This pr fixes `event-iterator` unused `ts-expect-error` directive.
> chore(event-iterator): use `ts-ignore` to silence compiler issue

- packages/iterator-utilities/src/lib/union.ts
This pr adds the missing ``` to the jsdoc
> docs(iterator-utilities): fix `union` jsdoc

- packages/iterator-utilities/src/lib/peekable.ts
The return type was wrong, it can never return `undefined`.
> fix(peekable): fix `peek()`'s return type

- packages/utilities/src/lib/types.ts
Fixes this warning:
> [warning] `Arr`, defined in
> `./projects/utilities/packages/utilities/src/lib/types.ts`,
> is referenced by `AbstractCtor.A` but not included in the documentation
> feat(utilities): expose `Arr` to the docs

- packages/string-store/src/lib/UnalignedUint16Array.ts
- packages/string-store/tests/lib/Schema.test.ts
- packages/string-store/tests/lib/UnalignedUint16Array.test.ts
Writing values over 16 bits bit by bit is inefficient, especially when it's the word size of the buffer. This PR optimizes the code by writing the value in at most two operations, significantly improving the performance for large values.
This makes writing operations the size of a word or larger do 16 times fewer operations.
> perf: implement fast word writing

- packages/snowflake/src/lib/Snowflake.ts
updates `timestampFrom` to operate on numbers instead of BigInts. This is faster whether the provided id is a string or bigint, even though sapphire stores the epoch as a bigint, and it is always accurate.
> perf(snowflake): optimize Snowflake.timestampFrom

- packages/string-store/src/lib/schema/SchemaStore.ts
- packages/string-store/tests/lib/SchemaStore.test.ts
BREAKING CHANGE: `serialize` no longer returns an `UnalignedUint16Array`, if you desire the old behaviour, use `serializeRaw`
> refactor(SchemaStore)!: introduce `serializeRaw`

- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
Replaces the now-deprecated ephemeral boolean with its equivalent message flag.
This was initially mentioned by camdzic in the utilities-development channel on Discord.
> refactor(discord.js-utilities): replace ephemeral with message flags

- packages/result/README.md
This pull request updates the documentation in the `packages/result/README.md` file to fix a broken link to the generated API documentation for the `@sapphire/result` package. Resolves #882.
Documentation updates:
* Corrected the link to the generated documentation by removing the outdated `/interfaces/IResult` path, ensuring the link now points to the correct base documentation page.
> docs: update documentation link for usage examples

- .github/workflows/auto-updater.yml
The [Automatic Data Update](https://github.com/sapphiredev/utilities/actions/workflows/auto-updater.yml) workflow currently fails once it tries to format the code. The cause of this failure is due to the prettier config needs to be built/transpiled into JS.
> Error:  Invalid configuration for file "/home/runner/work/utilities/utilities/packages/async-queue/src/index.ts":
Error:  Cannot find module '/home/runner/work/utilities/utilities/packages/prettier-config/dist/index.mjs' imported from /home/runner/work/utilities/utilities/.prettierrc.mjs
Error: Process completed with exit code 2.
As such, I have added a step that will run the build script for the prettier config.
> ci(auto-updater): build prettier config

- package.json
- packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
- packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
- yarn.lock
Discord.js 14.19.x utilises [discord-api-types #1190](https://github.com/discordjs/discord-api-types/pull/1190) of which includes a breaking change that renamed `APIMessageActionRowComponent` to `APIComponentInMessageActionRow`. Due to this, I have marked this PR as a breaking change for `discord.js-utilities`. 
Additionally, I have removed `discord-api-types` and `@discordjs/collection` from dev deps so that the versions that discord.js installs can be used instead. This is a change that the d.js docs "subpackages" tag suggests:
> discord.js includes multiple sub-packages, installing these separately can mess with internal code:
> ```
> npm uninstall discord-api-types @discordjs/rest @discordjs/builders
> yarn remove discord-api-types @discordjs/rest @discordjs/builders
> pnpm remove …
```
> fix(discord.js-utilities)!: update the action row component type
