sapphiredev/utilities

packages/discord-utilities/src/lib/regexes.ts
packages/prettier-config/tests/__snapshots__/prettier.test.ts.snap

fix(discord-utilities): mention regexes to strictly match their raw formats

---

packages/discord-utilities/src/lib/type-guards.ts

fix(discord-utilities): Correctly assert text channels in isTextChannel

---

jest.config.ts
packages/decorators/jest.config.ts
packages/decorators/src/core-decorators.ts
packages/decorators/src/utils.ts
packages/decorators/tests/core-decorators/apply-options.test.ts
packages/decorators/tests/core-decorators/create-function-precondition.test.ts
packages/decorators/tests/jest.setup.ts
packages/decorators/tests/mocks/MockInstances.ts
packages/utilities/tests/deepClone.test.ts

Based from https://github.com/skyra-project/decorators/blob/main/src/utils.ts#L89-L123.

feat(decorators): add createFunctionPrecondition, fixed build

---

packages/async-queue/src/lib/AsyncQueue.ts

wrap code example in code block

---

packages/eslint-config/README.md
packages/prettier-config/README.md
packages/ts-config/README.md

Y'all hard depend on those packages anyways

docs(prettier-config, eslint-config, ts-config): update installation instructions

---

packages/embed-jsx/src/index.ts
packages/embed-jsx/src/lib/EmbedJsx.ts
packages/embed-jsx/src/lib/errors/ValidationError.ts
packages/embed-jsx/src/lib/utils.ts
packages/embed-jsx/tests/__snapshots__/basic.test.tsx.snap
packages/embed-jsx/tests/basic.test.tsx
packages/embed-jsx/tests/errors.test.tsx

Adds data validation to embed, hopefully creating easier-to-debug error messages

feat(embed-jsx): add data validation

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

Shouldn't have removed the target argument, woops.

fix(discord.js-utilities): fix run method for PaginatedMessage

---

packages/discord.js-utilities/src/index.ts
packages/discord.js-utilities/src/lib/type-guards.ts
packages/discord.js-utilities/src/lib/utilities.ts
packages/discord.js-utilities/src/lib/utility-types.ts

**Functions**:
- Added `isGuildBasedChannelByGuildKey` (Skyra backport)
- Added `isThreadChannel` (Skyra backport)
- Added `isNsfwChannel` (Skyra backport)
- Added `canReadMessages` (Skyra backport)
- Added `canSendMessages` (Skyra backport)
- Added `canSendEmbeds` (Skyra backport)
- Added `canSendAttachments` (Skyra backport)
- Fixed `isDMChannel`
- Fixed `isGuildBasedChannel`
- Fixed `isNewsChannel`
- Fixed `isTextChannel`
**Types**:
- Added `ChannelTypes` (Skyra backport)
- Added `TextBasedChannelTypes` (Skyra backport)
- Added `VoiceBasedChannelTypes` (Skyra backport)
- Added `NonThreadGuildTextBasedChannelTypes` (Skyra backport)
- Added `GuildTextBasedChannelTypes` (Skyra backport)
- Added `ChannelTypeString` (Skyra backport)

feat(discord.js-utilities): add many more utilities

---

package.json
packages/discord.js-utilities/src/lib/type-guards.ts
packages/discord.js-utilities/src/lib/utility-types.ts
yarn.lock

- Added `GuildBasedChannelTypes`.
- Added `NonThreadGuildBasedChannelTypes`.
- :warning: **BREAKING CHANGE**: Increased strictness of `isCategoryChannel`.
- :warning: **BREAKING CHANGE**: Increased strictness of `isStageChannel`.
- :warning: **BREAKING CHANGE**: Increased strictness of `isStoreChannel`.
- :warning: **BREAKING CHANGE**: Increased strictness of `isThreadChannel`.
- :warning: **BREAKING CHANGE**: Increased strictness of `isVoiceChannel`.
- :warning: **BREAKING CHANGE**: Lowered strictness of `isDMChannel`.
- :warning: **BREAKING CHANGE**: Lowered strictness of `isGuildBasedChannel`.
- :warning: **BREAKING CHANGE**: Lowered strictness of `isGuildBasedChannelByGuildKey`.
- :warning: **BREAKING CHANGE**: Lowered strictness of `isNewsChannel`.
- :warning: **BREAKING CHANGE**: …

feat: backported more utilities and fixed bugs

---

packages/discord.js-utilities/src/lib/MessagePrompter/MessagePrompter.ts

fix(discord.js-utilities): mismatch between types

---

packages/discord.js-utilities/src/lib/utilities.ts

Basically backporting from Skyra as well as a new idea I had because of some Skyra code

feat(discord.js-utilities): add more typeguards + update checks

---

packages/snowflake/package.json
packages/snowflake/src/lib/Snowflake.ts
packages/snowflake/tests/lib/Snowflake.test.ts

fix(snowflake): fixed snowflake generating duplicate IDs

---

packages/utilities/src/lib/isNullOrUndefinedOrEmpty.ts
packages/utilities/tests/filterNullAndUndefined.test.ts
packages/utilities/tests/filterNullAndUndefinedAndEmpty.test.ts
packages/utilities/tests/isNullOrUndefinedOrEmpty.test.ts

Normally if you pass [] to isNullishOrEmpty it returns false but i fixed it in this PR

feat(utilities): add empty array to 'isNullishOrEmpty'

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

feat(PaginatedMessage): made separator text of embed field customizable

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

BREAKING CHANGE: `embedFooterSeperator` -> `embedFooterSeparator`

fix(PaginatedMessage): fixed `embedFooterSeperator` -> `embedFooterSeparator`

---

packages/eslint-config/src/index.ts
packages/eslint-config/tests/__snapshots__/eslint.test.ts.snap

fix(eslint-config): disable `@typescript-eslint/no-namespace`

---

packages/embed-jsx/src/index.ts
packages/embed-jsx/src/lib/EmbedJsx.ts

See https://github.com/sapphiredev/utilities/pull/212

fix(embed-jsx): remove instances of eslint-ignore comment

---

packages/utilities/src/index.ts
packages/utilities/src/lib/partition.ts
packages/utilities/tests/partition.test.ts

Code written 90% by GitHub Copilot tyvm

feat: add array partitioning

---

packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts

This is to ensure no ActionRows are created with both Buttons and SelectMenus

fix(PaginatedMessage): partition buttons and select menus

---

packages/discord-utilities/src/lib/limits.ts

Add:
MaximumButtonsPerActionRow
MaximumSelectMenusPerActionRow
MaximumItemsInSelectMenus
MaximumActionRows

feat(discord-utilities): add interaction limits

---

packages/discord.js-utilities/src/lib/utilities.ts

docs: fix `canReadMessages` documentation

---

packages/discord-utilities/src/lib/limits.ts

- Add limits related to upload size
- Add limit about maximum number of reactions
- Add limits about moderation
- Add limit about the biography length
Who made the biography length **190** characters ??? just why ??

feat(discord-utilities): add more limits

---

packages/eslint-config/src/index.ts

docs(eslint-config): fixed spelling for "Communities"

---

README.md

Fixed a wrong label for an NPM link.

docs(readme): update npm badge

---

packages/phisherman/src/lib/Phisherman.ts
packages/phisherman/src/lib/PhishermanTypes.ts

Phisherman recently added their documentation for [v2](https://docs.phisherman.gg/api/v2/) so i have added the missing methods for their specific endpoints

feat(phisherman): add more methods

---

packages/utilities/src/lib/deepClone.ts
packages/utilities/tests/deepClone.test.ts
packages/utilities/tests/mergeDefault.test.ts

fix: fixed date cloning

---

packages/snowflake/README.md

Gee thanks Kyra for updating the readme :(
#231 didn't update the readme

fix(snowflake): fixed the examples for `DiscordSnowflake` and `TwitterSnowflake`

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
packages/discord.js-utilities/src/lib/type-guards.ts

Well, that was mega awkward but apparently, the way we created the handler it was triggering on *all* handlers in the current channel as opposed to just the one that actually triggered it.

fix: fixed issues with `PaginatedMessage`

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

- Added `stopPaginatedMessageCustomIds` which we need to filter out custom Ids when the component have just been removed through a `stop` interaction so we do not call `.update` again.
- Always assign `this.response` to the latest interaction if that interaction was made by the `targetUser`
- Do not filter `interaction.message.id` to equal `this.response.id` because that won't work anymore with above
- Do not call `response.update` etc in the default stop action because the same code is called in `collector.on('end', ....)` and having it in both causes `interaction.update` to be called after the buttons are already gone.

fix(PaginatedMessage): fixes for modifying the components when the bot doesn't have VIEW_CHANNEL

---

packages/discord-utilities/src/lib/limits.ts

Lets document this more than the Discord dev docs do 🤔

feat(discord-utilities): add limits for autocomplete

---

packages/ratelimits/src/lib/RateLimit.ts

Just fix Type so I don't feel like I am using JS

fix(RateLimit): add default type to `RateLimit`'s type parameter to match its usage in `RateLimitManager`

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

fix(PaginatedMessage): allow overwriting `SelectMenu` options

---

packages/async-queue/package.json
packages/decorators/package.json
packages/discord-utilities/package.json
packages/discord.js-utilities/package.json
packages/embed-jsx/package.json
packages/eslint-config/package.json
packages/event-iterator/package.json
packages/fetch/package.json
packages/phisherman/package.json
packages/prettier-config/package.json
packages/ratelimits/package.json
packages/result/package.json
packages/snowflake/package.json
packages/stopwatch/package.json
packages/time-utilities/package.json
packages/utilities/package.json

feat: allow module: NodeNext

---

packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts

fix(PaginatedMessages): missing logic cases

---

packages/snowflake/package.json

docs(snowflake): fix typo in package description

---

.github/workflows/continuous-delivery.yml
packages/async-queue/cliff.toml
packages/decorators/cliff.toml
packages/discord-utilities/cliff.toml
packages/discord.js-utilities/cliff.toml
packages/eslint-config/cliff.toml
packages/event-iterator/cliff.toml
packages/fetch/cliff.toml
packages/phisherman/cliff.toml
packages/prettier-config/cliff.toml
packages/ratelimits/cliff.toml
packages/result/cliff.toml
packages/snowflake/cliff.toml
packages/stopwatch/cliff.toml
packages/time-utilities/cliff.toml
packages/ts-config/cliff.toml
packages/utilities/cliff.toml

- added owner check in workflow
- removed an extra `}` from cliff.toml

ci: add owner check in publish workflow

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

fix(paginated-message): fixed an issue cancelling a paginated message after an ephemeral reply

---

.github/workflows/auto-updater.yml
.github/workflows/labelsync.yml

these 2 workflows are failing everyday in my fork lol

ci: don't run update workflow on forks

---

packages/utilities/src/index.ts
packages/utilities/src/lib/lazy.ts
packages/utilities/tests/lazy.test.ts

Porting this over from Iriss/Nekokai

feat: add lazy

---

packages/result/src/lib/Option.ts
packages/result/src/lib/Result.ts

Fixes an issue found in https://github.com/sapphiredev/framework/pull/468

fix(result): resolve Unwrap type issues

---

packages/utilities/src/index.ts
packages/utilities/src/lib/getDeepObjectKeys.ts
packages/utilities/tests/getDeepObjectKeys.test.ts

Function I wrote for work and I figured I should port it over, improve the types and write unit tests for it

feat(utilities): add getDeepObjectKeys

---

packages/result/src/lib/Option/IOption.ts
packages/result/src/lib/Option/Some.ts
packages/result/src/lib/Result/IResult.ts
packages/result/src/lib/Result/Ok.ts

fix(result): make unwrap methods generic

---

packages/discord-utilities/src/lib/limits.ts
packages/time-utilities/src/lib/DurationFormatter.ts
packages/utilities/src/lib/debounce/index.ts

docs: fixed typos

---

packages/lexure/src/index.ts
packages/lexure/src/lib/util/util.ts
packages/lexure/tests/lib/util/util.test.ts

A little utility `lexure` had that we didn't. Most useful for https://github.com/sapphiredev/framework/pull/531.

feat: add `join` and `joinRaw`

---

.github/workflows/continuous-integration.yml
packages/stopwatch/README.md
packages/stopwatch/package.json
packages/stopwatch/src/index.ts
packages/stopwatch/src/tsconfig.json
packages/stopwatch/tests/browser/browser.test.ts
packages/stopwatch/tsup.config.ts
yarn.lock

feat: make @sapphire/stopwatch browser compitible

---

packages/utilities/src/index.ts
packages/utilities/src/lib/objectEntries.ts
packages/utilities/tests/objectEntries.test.ts

feat(utilities): add `objectEntries` function

---

packages/utilities/tsup.config.ts

fix(utilities): fixed output file extensions

---

packages/timestamp/README.md

I'm going to try to add usages to a lot of the packages that have it linked in their readme but not actually there

docs(timestamp): add usage

---

packages/time-utilities/README.md
packages/timer-manager/README.md

Excuse the first and fourth commit 🤭

docs(time-utilities): remove usage

---

packages/utilities/README.md

docs(utilities): add usage

---

.all-contributorsrc
.github/CODEOWNERS
.github/labels.yml
.github/workflows/continuous-integration.yml
.github/workflows/documentation.yml
.npm-deprecaterc.yml
README.md
packages/bitfield/.cliff-jumperrc.yml
packages/bitfield/.typedoc-json-parserrc.yml
packages/bitfield/CHANGELOG.md
packages/bitfield/README.md
packages/bitfield/cliff.toml
packages/bitfield/package.json
packages/bitfield/src/index.ts
packages/bitfield/src/lib/BitField.ts
packages/bitfield/src/tsconfig.json
packages/bitfield/tests/lib/BitField.test.ts
packages/bitfield/tests/tsconfig.json
packages/bitfield/tsconfig.eslint.json
packages/bitfield/tsup.config.ts
packages/bitfield/typedoc.json
packages/bitfield/vitest.config.ts
scripts/clean-full.mjs
scripts/clean.mjs
turbo.json
typedoc.json
yarn.lock

feat: add `@sapphire/bitfield` package

---

packages/bitfield/README.md
packages/bitfield/src/index.ts
packages/bitfield/src/lib/utilities.ts
packages/bitfield/tests/lib/utilities.test.ts

feat(utilities): add `enumToObject`

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

Resolves #553 
@Lioness100 can you please test this PR?

fix(PaginatedMessage): only add options and placeholder to the built-in StringSelectMenu

---

packages/utilities/src/lib/deepClone.ts
packages/utilities/tests/deepClone.test.ts
packages/utilities/vitest.config.ts

fix(utilities): add support for TypedArray to deepClone

---

packages/ts-config/README.md

Updated README.md to match the current config

chore(ts-config): Update README

---

packages/discord-utilities/src/lib/limits.ts

We might as well be thorough. This still only covers "Interactions" and "Resources" from the docs, not "Topics" or "Game SDK".

feat(limits): add more limits

---

packages/discord.js-utilities/src/lib/type-guards.ts

As [discussed on Discord here](https://discord.com/channels/737141877803057244/1145784526258307132/1145784526258307132)

fix(discord.js-utilities): revised type-guards for thread channels

---

packages/prettier-config/README.md

Add missing documentation change from Prettier v3.

docs(prettier-config): update readme

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

This was reported on Discord (https://discord.com/channels/737141877803057244/1169712258318880879). Took some figuring out where th root cause resides but in the end I found out then when N (N >= 2) users use the same command in the same channel and that command first defers with `ephemeral: true` then `handleCollect` was called multiple times when 1 of the users pressed any of the buttons of the `PaginatedMessage`. Apparently the `InteractionCollector` filter did not properly filter down to the specific user in this case and `handleCollect` would be called N amount of times where N is the amount of users that used the same command in the same channel. To resolve this we now check if the initial interaction was ephemeral or not and if it is then no one will be able to see the …

fix(paginatedmessage): fixed interacting with multiple users on multiple ephemeral interactions

---

packages/discord.js-utilities/src/lib/type-guards.ts

Spotted while working on #666. This makes it clearer what the functions do.

docs(typeguards): improve the docs for isAnyInteraction and isAnyInteractableInteraction

---

package.json
packages/fetch/README.md
packages/fetch/package.json
packages/fetch/tests/fetch.test.ts
packages/fetch/tests/vitest.setup.ts
packages/fetch/tsup.config.ts
packages/fetch/vitest.config.ts
packages/phisherman/package.json
packages/phisherman/src/lib/Phisherman.ts
packages/phisherman/tsup.config.ts
vitest.config.ts
yarn.lock

> [!IMPORTANT]
> Rebase & Merge
BREAKING CHANGE: This version and all subsequent versions require NodeJS v18 or above, or v16 with the `--experimental-fetch` flag

feat(fetch): drop cross-fetch, always use global fetch

---

packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts

> [!NOTE]
> ref: https://discord.com/channels/737141877803057244/1184968842183725126/1184968842183725126

fix(paginatedmessage): check for pageActions before throwing an error

---

.eslintrc
package.json
packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedFieldMessageEmbed.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageEmbedFields.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessageTypes.ts
packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
yarn.lock

> [!IMPORTANT]
> Rebase & Merge

Allow PaginatedMessage embeds to be footerless and expand documentation

---

.github/workflows/auto-updater.yml
.github/workflows/continuous-integration.yml
package.json
packages/utilities/package.json
scripts/dynamic-side-effects.mjs
scripts/subpath-updater.mjs
scripts/twemoji-regex-updater.mjs
turbo.json
yarn.lock

resolves #702
---
I was lowkey considering keeping it back until the 7th because of reasons but I didn't want to bother keeping it on just 1 laptop lol

fix: fixed bun compatibility for @sapphire/utilities

---

packages/eslint-config/README.md

Add instruction on how to use with Esline flat config.
If you guys want, I can include the code into the package, eg: `@sapphire/eslint-config/flat`.

docs(eslint-config): add note on how to use with flat config

---

packages/discord.js-utilities/src/lib/builders/MessageBuilder.ts

_created new pr had some conflicts with github_

feat(discord.js-utilities): add components to MessageBuilder

---

packages/discord.js-utilities/src/lib/type-guards.ts

Literally stealing from https://github.com/skyra-project/skyra/pull/2629

feat(discord.js-utilities): add attachment type guards

---

packages/utilities/README.md

Thanks @HigherOrderLogic for catching this!

docs(utilities): fix type in README

---

packages/utilities/src/lib/roundNumber.ts
packages/utilities/tests/roundNumber.test.ts

Simpler code and higher performance!
Before:
Now:

refactor: rewrite `roundNumber`

---

packages/async-queue/package.json
packages/bitfield/package.json
packages/cron/package.json
packages/discord-utilities/package.json
packages/duration/package.json
packages/fetch/package.json
packages/iterator-utilities/package.json
packages/lexure/package.json
packages/ratelimits/package.json
packages/result/package.json
packages/snowflake/package.json
packages/stopwatch/package.json
packages/string-store/package.json
packages/time-utilities/package.json
packages/timer-manager/package.json
packages/timestamp/package.json
packages/utilities/package.json
scripts/subpath-updater.cts

Resolves this warning from the build step:

fix: move browser imports

---

packages/async-queue/package.json
packages/bitfield/package.json
packages/cron/package.json
packages/discord-utilities/package.json
packages/duration/package.json
packages/fetch/package.json
packages/iterator-utilities/package.json
packages/lexure/package.json
packages/ratelimits/package.json
packages/result/package.json
packages/snowflake/package.json
packages/stopwatch/package.json
packages/string-store/package.json
packages/time-utilities/package.json
packages/timer-manager/package.json
packages/timestamp/package.json
packages/utilities/package.json
scripts/subpath-updater.cts

Reverts sapphiredev/utilities#826 which breaks compilation with at least Vite for at least @sapphire/fetch
Resolves #831

revert: "fix: move browser imports"

---

packages/string-store/src/lib/types/Constant.ts
packages/string-store/src/lib/types/Nullable.ts
packages/string-store/tests/lib/Schema.test.ts

Made possible with #848's changes 🎉

refactor: improve types for `t.constant` and `t.nullable`
